---
name: Run unit tests
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pytest
        run: |
          set -o pipefail
          uv run pytest | tee pytest-coverage.txt

      - name: Save PR number and coverage results
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/PR-number.txt
          cp ./pytest-coverage.txt ./pr/pytest-coverage.txt
          cp ./pytest.xml ./pr/pytest.xml

      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
